import sharp from 'sharp';
import type {MardColor,MardKitId,PatternAnalyzeResult,PatternCell,PatternConvertOptions,PatternSourceType,PatternUsage} from '@doulaozhuang/shared-types';
import {cleanNoise,hexRgb,mapColors,type Pixel} from './color';
export {rgbToOklab,labDistance} from './color';
export const ALGORITHM_VERSION='doulaozhuang-pattern-engine/1.0.0'; export const TARGET_WIDTHS=[24,29,40,58,75] as const;
const MAX_BYTES=10*1024*1024,MAX_PIXELS=40_000_000;
export class PatternEngineError extends Error{constructor(public code:string,message:string){super(message)}}
export interface EngineAnalysis extends PatternAnalyzeResult{crop:{left:number;top:number;width:number;height:number};gridPitch?:number}
export interface EngineResult{width:number;height:number;cells:PatternCell[];usage:PatternUsage[];totalBeads:number;colorCount:number;mirror:boolean;algorithmVersion:string;preview:Buffer;construction:Buffer}
async function load(input:Buffer){if(input.length>MAX_BYTES)throw new PatternEngineError('IMAGE_TOO_LARGE','图片不能超过 10 MB');const image=sharp(input,{failOn:'error',limitInputPixels:MAX_PIXELS}).rotate(),m=await image.metadata();if(!m.width||!m.height||!['png','jpeg','webp'].includes(m.format||''))throw new PatternEngineError('INVALID_IMAGE','仅支持 PNG、JPG/JPEG 和 WebP');if(m.width*m.height>MAX_PIXELS)throw new PatternEngineError('IMAGE_TOO_LARGE','图片像素不能超过 4000 万');return{image,width:m.width,height:m.height}}
async function cropAlpha(image:sharp.Sharp,w:number,h:number){const{data}=await image.clone().ensureAlpha().raw().toBuffer({resolveWithObject:true});let a=w,b=h,c=-1,d=-1;for(let y=0;y<h;y++)for(let x=0;x<w;x++)if(data[(y*w+x)*4+3]>20){a=Math.min(a,x);b=Math.min(b,y);c=Math.max(c,x);d=Math.max(d,y)}return c<0?{left:0,top:0,width:w,height:h}:{left:a,top:b,width:c-a+1,height:d-b+1}}
async function grid(image:sharp.Sharp,w:number,h:number){const scale=Math.min(1,900/Math.max(w,h)),W=Math.round(w*scale),H=Math.round(h*scale),data=await image.clone().resize(W,H).greyscale().raw().toBuffer(),x=new Array(W).fill(0),y=new Array(H).fill(0);for(let j=1;j<H;j++)for(let i=1;i<W;i++){const v=data[j*W+i];x[i]+=Math.abs(v-data[j*W+i-1]);y[j]+=Math.abs(v-data[(j-1)*W+i])}const correlation=(a:number[],p:number)=>{const mean=a.reduce((s,v)=>s+v,0)/a.length;let top=0,left=0,right=0;for(let i=p;i<a.length;i++){const u=a[i]-mean,v=a[i-p]-mean;top+=u*v;left+=u*u;right+=v*v}return top/Math.sqrt(left*right||1)};let best=-1,pitch=0;for(let p=5;p<=Math.min(60,Math.floor(Math.min(W,H)/4));p++){const s=(correlation(x,p)+correlation(y,p))/2;if(s>best){best=s;pitch=p}}return{confidence:Math.max(0,Math.min(1,best)),pitch:pitch/scale}}
async function patternRegion(image:sharp.Sharp,w:number,h:number,pitch:number){const{data}=await image.clone().removeAlpha().raw().toBuffer({resolveWithObject:true}),p=Math.max(4,Math.round(pitch)),cols=Math.floor(w/p),rows=Math.floor(h/p);if(cols<3||rows<3)return{left:0,top:0,width:w,height:h};const sample=(x:number,y:number)=>{const i=(Math.min(h-1,y)*w+Math.min(w-1,x))*3;return[data[i],data[i+1],data[i+2]]},border=[sample(1,1),sample(w-2,1),sample(1,h-2),sample(w-2,h-2)],bg=border.reduce((a,c)=>a.map((v,i)=>v+c[i]),[0,0,0]).map(v=>v/4),on:boolean[]=[];for(let y=0;y<rows;y++)for(let x=0;x<cols;x++){const c=sample(Math.round((x+.5)*p),Math.round((y+.5)*p)),d=Math.hypot(c[0]-bg[0],c[1]-bg[1],c[2]-bg[2]);on.push(d>45)}let best:number[]=[],seen=new Set<number>();for(let i=0;i<on.length;i++)if(on[i]&&!seen.has(i)){const q=[i],part:number[]=[];while(q.length){const n=q.pop()!;if(seen.has(n)||!on[n])continue;seen.add(n);part.push(n);const x=n%cols,y=Math.floor(n/cols);if(x)q.push(n-1);if(x<cols-1)q.push(n+1);if(y)q.push(n-cols);if(y<rows-1)q.push(n+cols)}if(part.length>best.length)best=part}if(best.length<4)return{left:0,top:0,width:w,height:h};const xs=best.map(i=>i%cols),ys=best.map(i=>Math.floor(i/cols)),x0=Math.max(0,Math.min(...xs)-1),y0=Math.max(0,Math.min(...ys)-1),x1=Math.min(cols-1,Math.max(...xs)+1),y1=Math.min(rows-1,Math.max(...ys)+1);return{left:x0*p,top:y0*p,width:Math.min(w-x0*p,(x1-x0+1)*p),height:Math.min(h-y0*p,(y1-y0+1)*p)}}
export async function analyzeImage(input:Buffer,sourceType:PatternSourceType):Promise<EngineAnalysis>{const{image,width,height}=await load(input);let crop=await cropAlpha(image,width,height);const thumb=await image.clone().resize(64,64).greyscale().raw().toBuffer();let delta=0;for(let i=1;i<thumb.length;i++)delta+=Math.abs(thumb[i]-thumb[i-1]);const complexity=Math.min(1,delta/(thumb.length*48)),g=sourceType==='existing_pattern_image'?await grid(image,width,height):undefined;if(g&&g.confidence<.22)throw new PatternEngineError('GRID_NOT_DETECTED','未检测到稳定网格，请上传包含完整格线的图纸');if(g)crop=await patternRegion(image,width,height,g.pitch);const best=complexity<.22?29:complexity<.42?40:58;return{sourceType,sourceWidth:width,sourceHeight:height,subjectRatio:crop.width*crop.height/(width*height),complexity,pixelScale:g?.pitch,gridConfidence:g?.confidence,crop,gridPitch:g?.pitch,suggestions:TARGET_WIDTHS.map(v=>({width:v,height:Math.max(1,Math.round(v*crop.height/crop.width)),recommended:v===best,detailRetention:v<best?'low':v===best?'medium':'high'}))}}
const kit=(id:MardKitId)=>Number(id.slice(5));
export async function convertImage(input:Buffer,sourceType:PatternSourceType,palette:MardColor[],options:PatternConvertOptions,known?:EngineAnalysis):Promise<EngineResult>{if(!TARGET_WIDTHS.includes(options.targetWidth))throw new PatternEngineError('INVALID_OPTIONS','不支持的图纸尺寸');const a=known||await analyzeImage(input,sourceType),{image}=await load(input),w=options.targetWidth,h=Math.max(1,Math.round(w*a.crop.height/a.crop.width));let pipe=image.extract(a.crop).resize(w,h,{fit:'fill',kernel:sourceType==='existing_pattern_image'?'nearest':'lanczos3'}).ensureAlpha();if(sourceType==='source_image'){if(options.preset==='clean')pipe=pipe.median(3);if(options.preset==='detail')pipe=pipe.sharpen({sigma:.8});pipe=pipe.modulate({saturation:1.13})}const{data}=await pipe.raw().toBuffer({resolveWithObject:true}),pixels:Pixel[]=[];for(let i=0;i<data.length;i+=4)pixels.push({r:data[i],g:data[i+1],b:data[i+2],a:data[i+3]});const mapped=mapColors(pixels,palette,Math.min(kit(options.kitId),palette.length));let indices=cleanNoise(mapped.indices,w,h,mapped.labs,options.preset||'balanced');if(options.removeBackground)removeConnectedBackground(indices,w,h);if(options.mirror)for(let y=0;y<h;y++)indices.splice(y*w,w,...indices.slice(y*w,(y+1)*w).reverse());const cells=indices.map((v,i)=>({row:Math.floor(i/w)+1,column:i%w+1,colorCode:v===null?null:palette[v].code,hex:v===null?null:palette[v].hex})),counts=new Map<number,number>();indices.forEach(v=>{if(v!==null)counts.set(v,(counts.get(v)||0)+1)});const usage=[...counts].map(([i,quantity])=>({code:palette[i].code,hex:palette[i].hex,quantity})).sort((a,b)=>b.quantity-a.quantity||a.code.localeCompare(b.code));return{width:w,height:h,cells,usage,totalBeads:usage.reduce((s,u)=>s+u.quantity,0),colorCount:usage.length,mirror:!!options.mirror,algorithmVersion:ALGORITHM_VERSION,preview:await preview(cells,w,h),construction:await sheet(cells,usage,w,h)}}
function removeConnectedBackground(v:(number|null)[],w:number,h:number){const corners=[v[0],v[w-1],v[(h-1)*w],v[w*h-1]].filter((n):n is number=>n!==null);if(!corners.length)return;const bg=corners.sort((a,b)=>corners.filter(n=>n===b).length-corners.filter(n=>n===a).length)[0],q=[0,w-1,(h-1)*w,w*h-1],seen=new Set<number>();while(q.length){const i=q.pop()!;if(seen.has(i)||v[i]!==bg)continue;seen.add(i);v[i]=null;const x=i%w,y=Math.floor(i/w);if(x)q.push(i-1);if(x<w-1)q.push(i+1);if(y)q.push(i-w);if(y<h-1)q.push(i+w)}}
const xml=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]!));
async function preview(c:PatternCell[],w:number,h:number){const s=20,b=c.map(v=>v.colorCode?`<rect x="${(v.column-1)*s}" y="${(v.row-1)*s}" width="${s}" height="${s}" fill="${v.hex}"/>`:'').join('');return sharp(Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="${w*s}" height="${h*s}"><rect width="100%" height="100%" fill="#fff"/>${b}</svg>`)).png().toBuffer()}
async function sheet(c:PatternCell[],u:PatternUsage[],w:number,h:number){const s=32,l=54,t=54,W=l+w*s+210,H=Math.max(t+h*s+50,t+u.length*24+50);let b='<rect width="100%" height="100%" fill="#fff"/>';for(const v of c){const x=l+(v.column-1)*s,y=t+(v.row-1)*s;b+=`<rect x="${x}" y="${y}" width="${s}" height="${s}" fill="${v.hex||'#fafafa'}"/>`;if(v.colorCode){const[r,g,z]=hexRgb(v.hex!);b+=`<text x="${x+s/2}" y="${y+20}" text-anchor="middle" font-family="Arial" font-size="10" font-weight="700" fill="${r*.299+g*.587+z*.114>155?'#15202b':'#fff'}">${xml(v.colorCode)}</text>`}}for(let x=0;x<=w;x++){const m=x>0&&x%5===0;b+=`<line x1="${l+x*s}" y1="${t}" x2="${l+x*s}" y2="${t+h*s}" stroke="${m?'#315b77':'#cbd5dc'}" stroke-width="${m?3:1}"/>`;if(x<w)b+=`<text x="${l+x*s+s/2}" y="${t-12}" text-anchor="middle" font-size="10">${x+1}</text>`}for(let y=0;y<=h;y++){const m=y>0&&y%5===0;b+=`<line x1="${l}" y1="${t+y*s}" x2="${l+w*s}" y2="${t+y*s}" stroke="${m?'#315b77':'#cbd5dc'}" stroke-width="${m?3:1}"/>`;if(y<h)b+=`<text x="${l-12}" y="${t+y*s+20}" text-anchor="end" font-size="10">${y+1}</text>`}b+=`<text x="${l+w*s+24}" y="${t+10}" font-size="16" font-weight="700">MARD 用量</text>`;u.forEach((v,i)=>{const y=t+36+i*24;b+=`<rect x="${l+w*s+24}" y="${y-14}" width="16" height="16" rx="3" fill="${v.hex}"/><text x="${l+w*s+48}" y="${y}" font-size="12">${xml(v.code)} · ${v.quantity}</text>`});return sharp(Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}">${b}</svg>`),{limitInputPixels:false}).png().toBuffer()}
