import {BadRequestException,ConflictException,Injectable,NotFoundException,RequestTimeoutException} from '@nestjs/common';
import {randomUUID} from 'node:crypto';import {extname} from 'node:path';import {analyzeImage,convertImage,PatternEngineError,type EngineAnalysis} from '@doulaozhuang/pattern-engine';import type {MardColor,PatternCell,PatternUsage} from '@doulaozhuang/shared-types';
import {PrismaService} from '../prisma/prisma.service';import {VaultsService} from '../vaults/vaults.service';import {MardPaletteService} from '../mard-palette/mard-palette.service';import {PatternStorageService} from './pattern-storage.service';import {ConvertPatternDto} from './dto/conversion.dto';
@Injectable() export class PatternConversionsService{constructor(private prisma:PrismaService,private vaults:VaultsService,private paletteService:MardPaletteService,private storage:PatternStorageService){}
 private async owned(userId:string,vaultId:string,id:string){await this.vaults.getOwnedVault(userId,vaultId);const c=await this.prisma.patternConversion.findFirst({where:{id,vaultId}});if(!c)throw new NotFoundException('转换草稿不存在或无权访问');return c}
 private fail(error:unknown):never{if(error instanceof PatternEngineError)throw new BadRequestException({code:error.code,message:error.message});throw error}
 async analyze(userId:string,vaultId:string,file:Express.Multer.File,sourceType:'source_image'|'existing_pattern_image'){await this.vaults.getOwnedVault(userId,vaultId);if(!file||!['image/png','image/jpeg','image/webp'].includes(file.mimetype))throw new BadRequestException({code:'INVALID_IMAGE',message:'仅支持 PNG、JPG/JPEG 和 WebP'});const id=randomUUID();try{const analysis=await analyzeImage(file.buffer,sourceType),sourcePath=await this.storage.write(id,`source${extname(file.originalname)||'.img'}`,file.buffer);await this.prisma.patternConversion.create({data:{id,vaultId,sourceType,status:'ANALYZED',sourcePath,analysis:analysis as any,expiresAt:new Date(Date.now()+86400000)}});return{conversionId:id,analysis}}catch(e){this.fail(e)}}
 async convert(userId:string,vaultId:string,id:string,dto:ConvertPatternDto){const draft=await this.owned(userId,vaultId,id);if(draft.status==='CONFIRMED')throw new ConflictException({code:'ALREADY_CONFIRMED',message:'已确认图纸不能覆盖'});const source=await this.storage.read(draft.sourcePath),palette=this.paletteService.getPalette().colors as MardColor[];try{const work=convertImage(source,draft.sourceType as any,palette,{...dto,preset:dto.preset||'balanced',mirror:!!dto.mirror,removeBackground:!!dto.removeBackground},draft.analysis as unknown as EngineAnalysis);const result=await Promise.race([work,new Promise<never>((_,reject)=>setTimeout(()=>reject(new PatternEngineError('CONVERSION_TIMEOUT','转换超过 30 秒')),30000))]);this.validate(result.cells,result.usage,result.width,result.height,result.totalBeads,Number(dto.kitId.slice(5)),new Set(palette.map(c=>c.code)));const previewPath=await this.storage.write(id,'preview.png',result.preview),constructionPath=await this.storage.write(id,'construction.png',result.construction);await this.prisma.patternConversion.update({where:{id},data:{status:'CONVERTED',options:dto as any,cells:result.cells as any,usage:result.usage as any,width:result.width,height:result.height,totalBeads:result.totalBeads,colorCount:result.colorCount,algorithmVersion:result.algorithmVersion,previewPath,constructionPath,errorCode:null}});return{...result,preview:undefined,construction:undefined,previewUrl:`/vaults/${vaultId}/pattern-conversions/${id}/assets/preview`,constructionUrl:`/vaults/${vaultId}/pattern-conversions/${id}/assets/construction`}}catch(e){const code=e instanceof PatternEngineError?e.code:'INVALID_RESULT';await this.prisma.patternConversion.update({where:{id},data:{status:'FAILED',errorCode:code}});if(code==='CONVERSION_TIMEOUT')throw new RequestTimeoutException({code,message:'转换超时，请降低尺寸后重试'});this.fail(e)}}
 private validate(cells:PatternCell[],usage:PatternUsage[],w:number,h:number,total:number,limit:number,codes:Set<string>){if(cells.length!==w*h||usage.length>limit||usage.some(u=>!codes.has(u.code))||usage.reduce((s,u)=>s+u.quantity,0)!==total||cells.filter(c=>c.colorCode).length!==total)throw new PatternEngineError('INVALID_RESULT','图纸结果校验失败')}
 async confirm(userId:string,vaultId:string,id:string,name:string){const c=await this.owned(userId,vaultId,id);if(c.status==='CONFIRMED'||c.confirmedPatternId)throw new ConflictException({code:'ALREADY_CONFIRMED',message:'该图纸已经保存'});if(c.status!=='CONVERTED'||!c.cells||!c.usage||!c.width||!c.height||!c.totalBeads||!c.colorCount)throw new BadRequestException('请先成功生成图纸');const options=c.options as any,usage=c.usage as unknown as PatternUsage[];return this.prisma.$transaction(async tx=>{const pattern=await tx.pattern.create({data:{vaultId,name:name.trim(),gridSize:c.width!,width:c.width,height:c.height,sourceType:c.sourceType,kitId:options.kitId,mirrored:!!options.mirror,cells:c.cells!,previewPath:c.previewPath,constructionPath:c.constructionPath,algorithmVersion:c.algorithmVersion,colorLimit:Number(options.kitId.slice(5)),totalBeads:c.totalBeads!,colorCount:c.colorCount!,sourcePath:c.sourcePath,usages:{create:usage.map(u=>({code:u.code,quantity:u.quantity}))}},include:{usages:true}});await tx.patternConversion.update({where:{id},data:{status:'CONFIRMED',confirmedPatternId:pattern.id}});return pattern})}
 async asset(userId:string,vaultId:string,id:string,kind:string){const c=await this.owned(userId,vaultId,id),path=kind==='source'?c.sourcePath:kind==='preview'?c.previewPath:kind==='construction'?c.constructionPath:null;if(!path)throw new NotFoundException('素材不存在');return this.storage.read(path)} }
